# 1 PLS

## 1.1 Process Gridded products

Descriptions of input data are helpful and clear. Data paths work with data that I unzipped from the drive folder that was shared with me. 

Total stem density plot seems logical. There are some points outside the state boundaries but they seem to correspond to islands that may not be included in the sf state boundaries. I will keep an eye on these later. 

AW: Yes, the grid cells outside of state boundaries are large islands (e.g., Isle Royale).

All of the species in the tree composition data are accounted for either by extracting their values or by intentionally excluding them. 

Plot of relative abundance seems like a reasonable check of data processing. The data also seems to have been processed successfully. Points conform to shape outlines, fractional compositions adhere to 0-1 range, broad-scale abundance patterns are reasonable and consistent with plots in the original publication for this input data (Paciorek et al., 2016). If these plots are going to be used in publication I would recommend a different color scale however since it is hard to see low levels of fractional composition in this one and there are many areas of low fractional composition. 

AW: That's fair. This is just a plot to check what the  data look like and I don't anticipate using a figure with this color palette.

Is the goal of limiting the fcomp domain to the total density domain (line ~217) to just get the data from the upper midwest? The comment is a little unclear about why you are doing this. 

AW: Yes. I added comments to explain this

Is the reason you plot total density in 242 and 259 to make sure nothing changed when you dropped the NAs? Otherwise, why are you plotting the exact same thing twice?

AW: Yes. In the first plot, there are NAs still but they're clear in color. So you see the full domain. Then I plot it again after dropping NAs to make sure that the grid still looks the same and the dimension of the grid
cells hasn't changed.

Species-specific relative abundance plots are in the correct spatial domain now (so that is probably what was being done ~217). Data is still within the correct boundaries both spatially and 0-1. Patterns of taxon abundance remain consistent with Paciorek et al., 2016 and earlier plots. 

Saving the processed data was completed successfully, the folder structure makes sense, and the file name is descriptive. 

## 1.2 Collate data

The file description is clear and helpful. Most of the input data descriptions are clear and useful. My only comment would be that it may be helpful for gridded_fcomp_density to add which script it was created in similarly to how the other inputs have the repo name and the output has where it will be used. 

AW: Added that it was created in the previous step

The initial plots remain the same as in the previous script. 

Soil data loaded correctly. Soil plots are consistent with the expected spatial domain as well as plots that were created at the end of the soil processing steps in the other repo. 

Same comments for the climate data as for the soils. 

Data saved correctly, the folder structure makes sense, and the name is reasonably descriptive though not as descriptive as previous file names. 

My only comment on this script is that the saved data could have a more descriptive name than xydata. 

## 1.3 Split data

I have the same comments here for the initial descriptions that I did for the last script. The overall script description is helpful and informative and the input and output data descriptions are clear but it may be helpful to add where processed input data is processed and saved. 

AW: Added

The checks in sections 2 and 3 of this script are appropriate for checking that the data processing is progressing as expected and are all coming back as passing that check. It may be beneficial to explain what is being checked in the comments surrounding the check. 

AW: Added

I am not sure this is necessary but you could add another explicit check after lines 103 and 105 to make sure that the number of grid cells in pls and fia data match the number of unique coordinates in either data set. However, they do match the number of rows in fia_coords and pls_coords so you should be good. 

AW: Thanks for the suggestion! Added

In the plot in line 116 I am intruiged by the fact that all of the FIA-only plots are on the borders of the region. Do you know why we don't have PLS data from those border areas?

AW: I think these grid cells just weren't counted in the original PalEON domain but their centroids are technically within our bounds so I included them here.

Partitioning of data into training and testing data is working correctly, follows the methods in the paper, and seems reasonable. The plots of the partitioning also seem suitably randomized though it may be interesting to see in/out subset by ecosystem type to verify that sampling approach. 

You could add an additional test after line 276 to verify that the in sample and out of sample row numbers equal the full pls row number. I checked and the row counts do match. 

AW: Thanks for the suggestion! Added

I still do no think xydata is a particularly descriptive file name but otherwise the saving was successful and the folder structure makes sense. 

I am not going to look at the deprecated folder but I would be happy to come back to it later if you think that would be helpful. 

AW: No, I'm just scared to delete anything yet! I actually didn't realize this was still on Github though so thanks for pointing it out. It should be removed now.

# 2 FIA

## 2.1 Join FIA

The overview of the file and descriptions of inputs are descriptive and useful. 

All data loaded correctly and there were no errors in the sections or joining. 

Filtering and joining seems reasonable but I will acknowledge that I do not have a great understanding of the FIA sampling design across years and plots.

AW: I'll just add that I extensively checked my filtering and joining methods with people who know more about FIA data: Kelly Heilman, her FIA colleagues, and Mike Dietze all provided advice on this section.

Saving worked successfully, file names are descriptive, and folder structure seems reasonable. I am a little confused about the distinction between the intermediate and processed data folders. I read the descriptions in the readme but the xydata, and gridded_fcomp_density also seem to be intermediate outputs from data processing steps so why are they in processed rather than intermediate? Is combined_COND_PLOT_TREE_SPECIES the only file that will be in this folder? If so, does it need its own folder?

AW: That's a good point. I updated all the scripts in sections 1 and 2, as well as the README, so that only the final versions of the data are in the processed directory. Thanks for thinking about this because I don't know what I was thinking.

## 2.2 Estimate Density Composition

File and input/output descriptions look good. 

The loop to assign IDs works and the descriptions are good but the number of print statements may be somewhat excessive. 

AW: No problem. I commented it out.

The assignment of matched coordinates makes sense to me but I am a little confused by why a site would have vs. would not have coordinates. Are the no_matched plots the ones with swapped/fuzzed data?

AW: Yes. I added a comment to explain this.

There are no comments at all between lines 389-471. Most of this is plotting but it would still be nice to have some explanation of what you are plotting and why as well as what you are taking away from these plots. 

AW: Sorry about that. I added comments throughout the section

Density plots for swapped/fuzzed vs non-swapped seem like a good way to check for broad-scale patterns in densities of each group which is well-complemented by the more numerical plots later on in the script.

Saving of data worked, folder structure is sensible, and file names are informative. 

## 2.3 Collate Modern Data

File headings are still helpful and clear. I have the same comment as above about adding where it was created to the gridded_all_plots data. 

AW: Added

Plots still look good. 

This one was fairly straightforward so I don't have a ton of comments. 

## 2.4 Split data

My only comment on this script is that if you wanted to you could add checks to make sure the amount of rows are the same like you did in 1.3 but otherwise it looks good. 

AW: Thanks! Added.

Again, this one is pretty straightforward so I don't have a ton of comments. 

# 3 NLCD

Skipping this one for now.  

# 4 RF_H2M

## 4.1 Fit Density All Covariates

Same comments on adding where data was processed for the input section. I may stop commenting on this in future sections to limit repetition in this review. 

The fitting of the random forests seems sensible and proceeded without errors. 

The path for saving the RFs on line 92 is specific to your computer rather than for the project. Is this what you meant in the beginning comments about the directory being saved according to your file structure?

Variable importance comments are helpful and clear and code is straightforward. The plots match both my data and the comments about the plots. 

The depth and importance plots are consistent with one another and the comments and code are clear. 

The partial effect plots also all look good though it would be helpful at the beginning of the code chunk to say what you are hoping to get from these plots as the comments are... sparse. 

this code takes forever to run but all the plots look good. 

## 4.2 Fit Density Climate Covariates

This is consistent with the methodology of 4.1 and the draft methods for the paper. My only comment on this script is you may want to add an additional comment about the save path at the end when the fit is actually being saved in addition to the header comments about saving to an external hard-drive. 

## 4.3 fit density redcovar

Variables selected are consistent with methods. 
Selection of node size and mtry seem reasonable. 
See notes from previous section about saving. 

## 4.4 Fit Density xy covariates

Node size and mtry selection follow the same steps as previous RF fitting and seem reasonable. 
Same comments about the saving but otherwise this one looks good. 

## 4.5 Density historical predictions
 Header comments are helpful and descriptive. 
 The names for each random forest predictions are not particularly descriptive and may make it challenging to remember which number corresponds to which set of predictors. 
 Otherwise the rest of the script is fairly straightforward and easy to follow. 
 
## 4.6 Density Modern Predictions

This is pretty much the exact same as the last script and all my comments are also the same as the last one. 

## 4.7 Density all figures

I still think that rf1-4 are not particularly descriptive names but otherwise all the processing and combining went smoothly and made sense. 
The historical prediction plots look good and are relatively consistent across the methods. 
So far the comments on the plotting code are helpful for understanding the goals of each plot. 
Calculations of correlations are relatively straightforward and seem good. 
Modern plots follow the same plotting procedures as the historical data and also seem to make sense and are created correctly.
I am not sure you need to save both the log and sqrt transformed scale plots but they are created quickly so it isn't that big of a deal. If you are curious, I prefer the log one. 
Similarly, with the change in prediction accuracy from historic to modern plots it may be helpful to only keep a couple of these for the finished github when you publish but they are great for while you are working on it. 

## 4.8 Fit Abundace All Covariates
 
 Selected variables are consistent with plots. 
 
## 4.9 Fit Abundance Climate Covariates

All analysis is consistent with previous workflow, makes sense, and is well-commented. 

## 4.10 Fit Abundance Reduced Covariates

Same as the previous script. 

## 4.11 Fit Abundance XY Covariates

Also the same as the previous script.

## 4.12 Abundance Historical Predictions

This is almost exactly the same as 4.5 and also seems good. It is clear, well-commented, and makes sense for what you are trying to do. 

## 4.13 Abundance Modern Predictions

Pretty much the same as the last script but it worked, was well-commented, and tests were all clear. 

## 4.14 Abundance Figures

The formatting and collating of data frames seems successful and well-commented. 
The plots of species fractional compositions were created successfully, seem consistent with expected distributions, and were commented. Species fractional composition is also consistent across models though the colors of the scale are whitish for lower fractional compositions (which is most of them) which pretty much blend in with the grey background. 
Scatter plots are also created successfully, clear, and consistent across models. 
The modern predictions followed exactly the same format as the historical ones and are also just as good. For some of the really low-abundance species I am not sure the best fit line is a great representation of the model fit but you have other ones so the combination of them is helpful (See beech around line ~5230 or dogwood around 5300). 

All the other plots seem to have executed correctly and are reasonable.

# 5 RF Modern to Historical

## 5.1 Fit Density All Covariates

Parameter adjustment continued as in previous sections. Variable importance matches what is commented in the code. These partial effects plots are going much faster than the previous ones which is nice. The rest of the scri[t was pretty similar to previous scripts and 

## 5.2 Fit Density Climate Covariates

This one was fairly straightforward but everything ran as intended, was well-commented, and made logical sense. 

## 5.3 Fit Density Reduced Covariates

Pretty much the exact same as the last script. Still ok. 

## 5.4 Fit Density XY Covariates

Same as the last 2. Still fine. 

## 5.5 Density Historical Predictions

All of the prediction-making seems good. The correct modern-trained models were loaded and all of the new data is the PLS data so the code is doing what it says it should be doing. 

## 5.6 Modern Density Predictions
Correct (modern-trained) models loaded and correct out-of-sample moderns test data used. They are also saved in a reasonable place.

## 5.7 Density Figures

Plots seem reasonable and results are consistent with the results we have discussed. I am a little surprised that the modern predicted minus observed are so far from the 1:1 line in 423-482, do you know why that is?

## 5.8 Fit Abundance All Covariates

Variable importancce consistent with comments. 
The partial effects plots loaded correctly and seem good.

## 5.9 Fit Abundance Climate Covariates

All code in this section progressed similarly to previous sections and was logical and did what was described in the methods. 

## 5.10 Fit abundance reduced covariates
 
 Pretty much the same as the previous section but it went well and made sense. 
 
## 5.11 Fit Abundance XY covariates

Appropriate variables were selected, fitting was logical and methodology was consistent with previous sections.

## 5.12 Abundance historical predictions

Appropriate models loaded and correct data used to predict. Models saved in logical locations. The code does what it says it does. 

## 5.13 Abundance Modern Predictions

Appropriate models loaded and correct data used to predict. Models saved in logical locations. The code does what it says it does. 

## 5.14 Abundance Figures

Formatting of results is logical and consistent with previous methodology. Plots seem appropriate for checking that predictions are reasonable as well as visualizing differences in predictive accuracy.Lots of plots.
