---
title: "Outline"
author: "Alyssa Willson"
date: "2023-10-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following is the outline that Jason drafted on the whiteboard during one of our intial meetings. I didn't add/remove content except for where I couldn't read the exact words that were on the whiteboard or where I felt clarification was necessary.

**WORKING TITLE**: The problem of overfitting in predictive ecology: accounting for temporal dynamics demonstrates the pervasiveness of multiple ecosystem states at the regional scale

**AUTHORS**: Alyssa M. Willson, Cazimir Kowalski, Kelly A. Heilman, Ian Shuman, Jason S. McLachlan

- Possibly to add: Carla Staver, Christopher Paciorek, Stefano Castruccio

**Outline**:

- Introduction
  - Topic: Overfitting SDMs leads to bias in detecting multiple ecosystem states
    - Lit: Higgins, etc. $\rightarrow$ 1:1 relationship between environment and ecosystem state presence/absence
    - Danger of overfitting (argument of the statistical importance of avoiding overfitting)
    - This extends beyond multiple ecosystem states
    - The consequence is failure to accurately predict ecosystem state distributions under future conditions
  - One way of overfitting is to fit a process at one time period and make temporal predictions
    - We need validation across time to have confidence in temporal processes
    - The existence and predictibilty of multiple ecosystem states are inherently temporal questions, which necessitates fitting and validation over time
  - $H_0$: There is a 1:1 relationship between the environment and vegetation. We can quantify this relationship by fitting a hierarchical SDM using historical data from the PLS period. This relationship will persist in the modern period, and prediction of ecosystem state in the modern period will be accurately predicted using environmental data from the modern period and the statistical relationship between environment and vegetation from the historical period.
- Methods
  - Risks to minimize:
    - Too specific
      - Spatially: at the regional scale, specific to the Upper Midwest
      - Statistically: self-fulfilling prophecy of identifying multiple ecosystem states based on the data selected \& modeling procedure
    - Not specific enough
      - Not including all the environment variables that could drive ecosystem state distributions
    - Environmental change from the historical to modern period
      - Change in some unquantifiable environmental variable (e.g., storm return interval), not anthropogenic disturbance, drives differences in ecosystem state distribution between the historical and modern periods
      - Arguments
        - Environmental space covers PLS \& FIA
        - Little change in some environmental drivers: topography, soils
        - Where possible, we explicitly account for differences in environmental space: climate, possibly soil texture & mositure content
  - MOST DIRECT
    - Accounting for above risks
    - Using hierarchical SDM
    - Fit to historical period, predict modern period, validate using FIA data
  - Machine learning
    - More flexible complementary approach using same environmental and response variable data
  - Spatial extent: Illinois, Indiana, Upper Michigan, Wisconsin, Minnesota
- Results
  - Reject the null hypothesis
- Discussion
  - Higgins and others are thinking about the concept of multiple ecosystem states incorrectly by overfitting to one time period/assuming that space-for-time substitution adequately captures ecosystem variability
  - Making dynamic predictions requires fitting \& validation over time
  - This also applies to ecological inference outside of multiple ecosystem state investigations