---
title: "Timeline"
author: "Alyssa Willson"
date: "2023-10-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document highlights some main tasks that I think should be accomplished for this project and when I expect they should be completed. I have included who I think is the best person to work on different tasks. Ideally, I would like folks to revise this by pointing out when a deadline is unrealistic, adding tasks that I missed, etc.

**Tasks:**

1. Literature review
  - Read Shuman's manuscript draft
  - Collate literature on environmental covariates of vegetation change
    - Climate drivers
    - Soil characteristics
    - Topographic charactersitics (although likely won't include)
    - Anything else? Latitude/longitude?
    - Literature should be collated in the shared Zotero library. It would be great if you could add short notes describing the main point of the paper in the "notes" section
2. Gather data
  - Collect point-level PLS data for entire region
    - Presence/absence of each ecosystem state at each corner
    - Treating ecosystem state as presence/absence allows us to account for covariance between ecosystem states
    - The alternative would be one response variable of ecosystem state with three factor levels: savanna, prairie, forest
  - Collect point-level environmental drivers for entire region. Likely to include (at least to start):
    - Average annual temperature
    - Total annual precipitation
    - Soil texture
    - Soil wetness
    - Presence of floodplain
    - ??
  - Environmental conditions for both historical and modern eras
  - All collected data should be put in appropriate subdirectories of the "data/raw" directory
3. Fit historical vegetation-environment relationship
  - Build hierarchical model including
    - Linear model of vegetation-environment relationship
    - Pontentially a spatial process but I'm not sure it's necessary yet
    - Latent covariance between ecosystem states
      - In this paper, we can assume that the covariance accounts for "missing" environmental processes, minimizing a couple of the risks above
4. Predict ecosystem states in the modern era
  - Treat as out-of-sample prediction from the model above
5. Compare predicted ecosystem states to the ecosystem type recorded by USGS NLCD
  - I am proposing to use satellite imagery and not FIA because FIA is **Forest** Inventory and Analysis and we really care about where there is and is *not* forest

**Timeline**

- November \& December 2023
  - **Caz \& Jason**: Read Ian's manuscript
    - Caz: focus specifically on methods. can also provide comments
    - Jason: provide comments but also good framing for this project
  - **Caz**: collate literature on environmental predictors of ecosystem distribution
    - In the **Upper Midwest**, what drives ecotone boundaries?
      - Species range shifts?
    - Then look at **paleo** literature
      - Any attempts globally to look at climate-vegetation relationship at paleo time scale
    - Then look at **NPP** literature
      - Tree ring analyses for climate
      - Shorter time scales? Towers?
      - This can be brief but I think some of this could be really relevant
    - **SDM** literature
      - What is typically used as environmental predictors in space-for-time substitution SDM literature?
  - **Alyssa**: nail down model structure
    - Include spatial covariance?
    - Format of response variable(s)
    - Whether or not to include response variable covariance
    - Efficiency checks
- January 2024
  - **Caz**: determine what environmental variables should be used
    - Should look similar to what Kelly and Ian have used, but should be more thoroughly justified and could be updated
    - This needs to be done early in the month to faciliate gathering the data
  - **Caz**: collate SDM literature
    - Understand how SDMs are typically fit and how prediction works
    - Underlying structure of SDMs for vegetation prediction
  - **Alyssa**: gather data
    - Climate covariates for historical period from PRISM
    - Climate covariates for modern period from PRISM (for consistency)
    - Soil covariates for historical period from ??
    - Soil covariates for modern period from USGS
    - Other covariates?
- February-March 2024
  - **Caz**: prepare modern data
    - Use USGS NLCD to classify vegetation at the same point locations in the modern period
      - https://www.usgs.gov/centers/eros/science/national-land-cover-database
    - Determine how to convert NLCD data to presence of forest, savanna, prairie ecosystem states
    - Determine which epoch(s) to use
    - Format data so that there is a metric of ecosystem state at each corner for comparison
    - Figure out what to do with anthropogenic land uses (like should we just take out all the cropland and cities?)
  - **Alyssa**: run model
    - It will assuredly break which is why I'm giving myself so long for this task
- April 2024
  - **Alyssa**: out-of-sample prediction
    - Use modern data and run the model in a predictive format
  - **Alyssa**: visualization
    - Data maps
      - Environmental conditions in modern era
      - Environmental conditions in historical era
      - Ecosystem distributions in modern era
      - Ecosystem distributions in historical era
    - Coefficient estimates for historical era
    - In-sample prediction for historical era
    - Out-of-sample prediction for modern era
    - Dissimilarlity index for out-of-sample prediction vs. data
  - **Alyssa**: new outline of paper
    - Read literature
    - Based on what we actually did and the literature that was collated, write new outline
  - **Caz \& Jason**: provide feedback for outline
- May 2024
  - **Alyssa**: draft introduction
  - **Caz \& Jason**: provide feedback on figures
    - Confusing?
    - Missing something?
  - **Caz \& Jason**: provide introduction feedback
- June 2024
  - **Alyssa**: draft methods \& results
  - **Caz \& Jason**: provide feedback
- July 2024
  - **Alyssa**: draft discussion
  - **Caz \& Jason**: provide feedback
- August 2024
  - **Alyssa**: draft revisions
  - **Alyssa**: present at ESA
- September 2024
  - SUBMIT